server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
spring:
  application:
    name: demo-spring-security
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USER_NAME:sa}
    password: ${DATABASE_USER_PASSWORD:sa}
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER